export const FETCHING_LOTTERY_DETAIL = "FETCHING_LOTTERY_DETAIL";
export const FETCHING_LOTTERY_DETAIL_SUCCESS = "FETCHING_LOTTERY_DETAIL_SUCCESS";

export const FETCHING_ALLOWED_COUNT = "FETCHING_ALLOWED_COUNT";
export const FETCHING_ALLOWED_COUNT_SUCCESS = "FETCHING_ALLOWED_COUNT_SUCCESS";

export const FETCH_LOTTERY_MANAGER = "FETCH_LOTTERY_MANAGER";
export const FETCH_LOTTERY_MANAGER_SUCCESS = "FETCH_LOTTERY_MANAGER_SUCCESS";

export const FETCH_LOTTERY_IDS = "FETCH_LOTTERY_IDS";
export const FETCH_LOTTERY_IDS_SUCCESS = "FETCH_LOTTERY_IDS_SUCCESS";

